name: Terraform Destroy

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          ref: main  # Specify the branch name here

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0  # Adjust version as needed

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
