name: Terraform

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout specific branch
        uses: actions/checkout@v2
        with:
          ref: main  # Specify the branch name here

      # Configure AWS CLI with credentials
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0  # Adjust version as needed

      - name: Initialize Terraform
        run: |
          cd controltower
          terraform init

      - name: Terraform Plan
        run: |
          cd controltower
          terraform plan

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'  # Only run apply if on the specific branch
        run: |
          cd controltower
          terraform apply -auto-approve
